POST http://localhost:3000/api/save-wishlist
Content-Type: application/json

{
"owner": "test.user",
"wishes": [
    {
        "content": "wish item 1b"
    },
    {
        "content": "wish item 2"
    }
]
}
###

POST http://localhost:3000/api/register
Content-Type: application/json

{
  "username": "test-user",
  "password": "test-password"
}
###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "test-user",
  "password": "test-password"
}

###
GET http://localhost:3000/api/wishlist/test-user
Content-Type: application/json
